libs/shared/hooks/.eslintrc.json, libs/shared/hooks/README.md, libs/shared/hooks/package.json, libs/shared/hooks/project.json, libs/shared/hooks/src/index.ts, libs/shared/hooks/src/useCryptoIcon.ts, libs/shared/hooks/tsconfig.json, libs/shared/hooks/tsconfig.lib.json, libs/shared/hooks/vite.config.ts, libs/shared/ui/src/Icons/TokenIconRevamp.tsx, libs/shared/ui/src/Icons/index.ts, package.json, tsconfig.base.json, yarn.lock
https://github.com/rollup/plugins/tree/master/packages/dynamic-import-vars#limitations
=> feat: add new token icon component

libs/mstable/explore/src/components/CoreFeatureCard/DefaultCoreFeatureCard.tsx, libs/mstable/explore/src/components/CoreFeatureCard/MobileCoreFeatureCard.tsx, libs/mstable/explore/src/components/CoreFeatureCard/index.tsx, libs/mstable/explore/src/components/CoreFeatureCard/types.ts, libs/mstable/explore/src/components/CoreVaultCard/components/DefaultVaultCard.tsx, libs/mstable/explore/src/components/CoreVaultCard/components/MobileVaultCard.tsx, libs/mstable/explore/src/components/CoreVaultCard/types.ts, libs/mstable/explore/src/components/CoreVaultTableRow.tsx, libs/mstable/explore/src/components/Vaults.tsx, libs/mstable/explore/src/views/Explore.tsx, libs/mstable/vault/src/components/Strategy/components/Fees.tsx, libs/shared/constants/src/core-vaults/index.ts, libs/shared/constants/src/core-vaults/optimism/ethy.ts, libs/shared/constants/src/core-vaults/optimism/usdmny.ts, libs/shared/constants/src/core-vaults/optimism/usdy.ts, libs/shared/constants/src/types.ts, libs/shared/ui/src/TradingInput/index.tsx
Adds main Toros yield vaults.
Cleans up home page.
=> feat: display toros yield vaults

libs/mstable/flatcoin/src/components/Positions/index.tsx, libs/mstable/flatcoin/src/components/TradingPanel/index.tsx, libs/mstable/flatcoin/src/components/TradingPanel/state.ts, libs/mstable/flatcoin/src/hooks/useChartData.ts, libs/mstable/flatcoin/src/state.ts, libs/mstable/flatcoin/src/types.ts, libs/shared/hooks/src/index.ts, libs/shared/hooks/src/useChartData.ts, libs/shared/providers/src/prices/hooks.ts, libs/shared/providers/src/prices/types.ts
Adds ETH price chart to LeveragedEth side.
Simplifies PositionType.
=> feat: add leveraged eth chart

apps/mstable/src/clients/wagmi.ts, libs/mstable/vault/src/components/Strategy/components/Assets/index.tsx, libs/shared/constants/src/network.ts, package.json, yarn.lock
1. Fixed block explorer link when wallet is not connected
=> fix: block explorer links

libs/lts/burn/src/components/BurnForm/components/InputStep/index.tsx
[Link to Trello card](https://trello.com/c/whyqB3DK/3345-show-velodrome-mta-swap-link-for-wallets-with-0-mta-balance)
=> fix: show velodrome MTA swap link for wallets with zero MTA balance

apps/lts/src/components/Topnav.tsx, libs/shared/constants/src/mstable.ts, package.json
[Link to Trello card](https://trello.com/c/tfIvGXkl/3357-make-logo-on-legacy-app-go-back-to-landing-page-mstableorg)
Updates lts app logo link.
=> feat: update lts logo link

libs/shared/constants/src/dhedge.ts
=> fix: dhedge api url

libs/shared/constants/src/dhedge.ts
This reverts commit e77f598ecfc37003d3aaa8fa2cb09ccee90364c9.
=> Revert "fix: dhedge api url"

apps/mstable/i18n/en.json, apps/mstable/src/assets/lang/en.json, libs/mstable/flatcoin/src/components/Positions/AnnouncedOrders.tsx, libs/mstable/flatcoin/src/state.ts, libs/mstable/flatcoin/src/types.ts, libs/mstable/flatcoin/src/utils/index.ts, libs/mstable/flatcoin/src/views/Flatcoin.tsx
=> feat: add styling to announced orders card

libs/lts/constants/src/saves.ts
=> feat: add imUSD redeem support

libs/mstable/flatcoin/src/components/Positions/Leverage/ApproveLeveragePositionButton.tsx, libs/mstable/flatcoin/src/components/Positions/Leverage/CloseLeveragePositionModal.tsx, libs/mstable/flatcoin/src/hooks/state/useUserLeveragePositions.ts, libs/mstable/flatcoin/src/state.ts, libs/mstable/flatcoin/src/types.ts
Use `Viewer` contract to fetch user leveraged positions
=> refactor: useUserLeveragePositions hook

libs/mstable/flatcoin/src/components/Jumbo/index.tsx, libs/mstable/flatcoin/src/state.ts, libs/mstable/flatcoin/src/types.ts, libs/mstable/flatcoin/src/utils/contracts.ts
=> feat: display flatcoin tvl

apps/mstable/index.html
[Link to Trello card](https://trello.com/c/j6h2T26d/3336-add-mstable-static-social-media-preview-card)
Adds preview image.
=> feat: setup preview image

apps/mstable/src/components/Footer/index.tsx, apps/mstable/src/components/Topnav/index.tsx, libs/mstable/flatcoin/src/components/Positions/Leverage/CloseLeveragePositionButton.tsx, libs/mstable/flatcoin/src/components/Positions/Leverage/CloseLeveragePositionModal.tsx, libs/shared/constants/src/tokens/baseGoerli.ts
=> feat: remove mStable branding from flatcoin page

apps/mstable/src/routes.tsx, libs/mstable/flatcoin/src/components/Jumbo/index.tsx, libs/mstable/flatcoin/src/components/TradingPanel/index.tsx, libs/mstable/flatcoin/src/components/TradingPanel/state.ts, libs/mstable/flatcoin/src/hooks/index.ts, libs/mstable/flatcoin/src/hooks/useChartData.ts, libs/mstable/flatcoin/src/hooks/useFlatcoinType.ts, libs/mstable/flatcoin/src/hooks/useIsLeveragedType.ts, libs/mstable/flatcoin/src/hooks/usePostionTypeNameMap.ts, libs/mstable/flatcoin/src/state.ts, libs/mstable/flatcoin/src/types.ts, libs/mstable/flatcoin/src/utils/index.ts, libs/mstable/flatcoin/src/views/Flatcoin.tsx
Position type update: leveragedeth -> leveraged
Derives position type name from tokens.
=> feat: use tokens name for position type label

libs/mstable/flatcoin/src/components/Performance/components/Controls.tsx, libs/mstable/flatcoin/src/components/Performance/components/TokenData.tsx, libs/mstable/flatcoin/src/components/Performance/index.tsx
Displays token price inside performance section
=> feat: display token price

.github/workflows/flatcoin-dev.yml
Added new github action for deploying `feat/flatcoin-page` branch 
=> feat: add flatcoin dev github action

libs/mstable/vault/src/components/Apy/index.tsx
1. Showed best APY value when apy period is not defined.
=> feat: show best available vault apy value

apps/mstable/i18n/en.json, apps/mstable/src/assets/lang/en.json, apps/mstable/src/components/Footer/index.tsx, libs/mstable/vault/src/components/VaultJumbo/index.tsx, libs/mstable/vault/src/views/Vault.tsx, libs/shared/constants/src/mstable.ts, package.json, yarn.lock
[Link to Trello card](https://trello.com/c/JZRrwm9S/3383-add-relevant-links-to-dhedge-and-toros-inside-of-mstable-yield-app)
Adds general dHedge link on footer and direct vault link on header.
=> feat: display dhedge links

apps/lts/src/clients/wagmi.ts, apps/mstable/src/clients/wagmi.ts
Temporary disabled `Ledger` wallet
[Issue](https://twitter.com/apoorvlathey/status/1735281719216071019?t=P_WrJACrtZlyL2G7xfFaIA&s=19)
=> fix: temporary disable Ledger wallet in both apps

libs/mstable/vault/src/components/VaultJumbo/index.tsx
=> fix analyticsHref

libs/mstable/vault/src/components/Strategy/components/Fees.tsx, libs/mstable/vault/src/components/TradingPanel/TradingRecap/TradingTransactionOverview.tsx, package.json, yarn.lock
1. Added exit fee info to trading panel
2. Added exit fee info to fees section 
=> feat(Fees): handle fees upcoming breaking changes

package.json, yarn.lock
=> feat(Core UI Kit): update version

libs/dhedge/withdraw/src/components/BurnForm/components/InputStep/index.tsx
=> feat(dHEDGE V1 Deprecation): add wallet address hint message

libs/lts/burn/src/components/BurnForm/components/InputStep/components/SubmitButton.tsx
=> fix(MTA Burn): burn transaction config dependencies

libs/mstable/vault/src/components/TradingModal/TradingModalSummary.tsx, libs/mstable/vault/src/components/TradingPanel/TradingInputs/TradingInput/index.tsx, libs/mstable/vault/src/components/TradingPanel/TradingRecap/TradingTokensOverview.tsx, libs/mstable/vault/src/components/TradingPanel/TradingRecap/TradingTransactionOverview.tsx, libs/shared/constants/src/core-vaults/optimism/mhrvst.ts, libs/shared/constants/src/types.ts, package.json, yarn.lock
https://github.com/dhedge/core-ui-kit/releases/tag/v0.4.8-legacy
=> fix: Remove USDC from withdraw tokens for Meta Harvester
